#!/usr/bin/env bash
# This bash script configures Nginx server so that /redirect_me is redirected to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi
