#!/usr/bin/env bash
# Install and configure HAProxy load balancer
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

# Enable load balancer
sudo sed -i 'aENABLED=1\n' /etc/default/haproxy

# Config load balancer with web servers
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "\$a\\\nfrontend 194456-lb-01\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\nbackend web-backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver 194456-web-01 100.26.151.233:80 check\n\tserver 194456-web-02 54.152.235.113:80 check\n" /etc/haproxy/haproxy.cfg

sudo service haproxy start
