#!/usr/bin/env bash
#This bash script displays Best School 10 times,
#but for the 9th iteration, display Best School and then Hi on a new line.

count=1
while [ $counter -le 10 ];
do
	if [ $counter -eq 9 ];
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
