#!/usr/bin/env bash
#bash script that displays:
#the content of the current directory
#in a list format
#where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
	echo "$file" | cut -d "-" -f 2
done
